---

- name: "Amazon - installing httpd"
  yum:
    name: httpd
    state: present
 
- name: "Amazon - installing php"
  shell: amazon-linux-extras install php7.4 -y
 
- name: "Amazon - creating httpd conf file from template"
  template:
    src: "./templates/httpd.conf.j2"
    dest: "/etc/httpd/conf/httpd.conf"
 
- name: "Amazon - creating virtualhost from template"
  template:
    src: "./templates/virtualhost.conf.j2"
    dest: "/etc/httpd/conf.d/{{ httpd_domain }}.conf"
    owner: "{{ httpd_owner }}"
    group: "{{ httpd_group }}"
 
- name: "Amazon - creating document root"
  file:
    path: "/var/www/html/{{ httpd_domain }}"
    state: directory
    owner: "{{ httpd_owner }}"
    group: "{{ httpd_group }}"
 
- name: "Amazon - installing mariadb"
  yum:
    name:
      - mariadb-server
      - MySQL-python
    state: present
 
- name: "Amazon - restarting & enabling mariadb service"
  service:
    name: mariadb
    state: restarted
    enabled: true
 
- name: "Amazon - updating root pass"
  ignore_errors: true
  mysql_user:
    login_user: root
    login_password: ""
    name: root
    password: "{{ mariadb_root_pass }}"
    host_all: true
 
- name: "Amazon - removing anonymous users"
  mysql_user:
    login_user: root
    login_password: "{{ mariadb_root_pass }}"
    name: ""
    password: ""
    host_all: true
    state: absent
 
- name: "Amazon - creating db"
  mysql_db:
    login_user: root
    login_password: "{{ mariadb_root_pass }}"
    name: "{{ mariadb_extra_db }}"
    state: present
 
- name: "Amazon - creating user"
  mysql_user:
    login_user: root
    login_password: "{{ mariadb_root_pass }}"
    name: "{{ mariadb_extra_user }}"
    password: "{{ mariadb_extra_pass }}"
    state: present
    host: "%"
    priv: "{{ mariadb_extra_db }}.*:ALL"
 
- name: "Amazon - downloading wp archive"
  get_url:
    url: "{{ wp_url }}"
    dest: "/tmp/wordpress.tar.gz"
 
- name: "Amazon - extracting wp archive"
  unarchive:
    src: "/tmp/wordpress.tar.gz"
    dest: "/tmp/"
    remote_src: true
 
- name: "Amazon - copying wp files"
  copy: 
    src: "/tmp/wordpress/"
    dest: "/var/www/html/{{ httpd_domain }}/"
    remote_src: true
    owner: "{{ httpd_owner }}"
    group: "{{ httpd_group }}"
 
- name: "Amazon - creating wp-config file from template"
  template:
    src: "./templates/wp-config.php.j2"
    dest: "/var/www/html/{{ httpd_domain }}/wp-config.php"
    owner: "{{ httpd_owner }}"
    group: "{{ httpd_group }}"
 
- name: "Post Installation - restarting services"
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items: 
    - httpd
    - mariadb
 
- name: "Post Installation - cleanup"
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - "/tmp/wordpress/"
    - "/tmp/wordpress.tar.gz"
